version: "3.8"

services:

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - tempo
      - loki

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  tempo:
    image: grafana/tempo:latest
    ports:
      - "3200:3200"
      - "4317:4317"
      - "4319:4318"
    volumes:
      - ./tempo.yml:/etc/tempo.yml
    command:
      - "-config.file=/etc/tempo.yml"

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.96.0
    command:
      - "--config=/etc/otel-collector-config.yml"
    ports:
      - "4318:4317"
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml

  workplacement-worker:
    build:
      context: ../src/WorkPlacementWorker
    depends_on:
      - otel-collector
    environment:
      - DOTNET_ENVIRONMENT=Development
